### ISSUE TITLE
请问怎样挂载

### ISSUE THREAD

**Issue by dalaoJAck** [gaoyb7/rclone-release#10]
需要安装其它的软件吗，目前仅抓取了cookie没有找到挂载教程

**Comment by gaoyb7** [comment]
> 需要安装其它的软件吗，目前仅抓取了cookie没有找到挂载教程

![image](https://user-images.githubusercontent.com/9281603/201038648-3c48f849-8bfb-4adb-82c9-c4d66379d09d.png)
