### ISSUE TITLE
挂载本地磁盘失败

### ISSUE THREAD

**Issue by dalaoJAck** [gaoyb7/rclone-release#14]
webdave能正常打开，但挂载本地磁盘一直失败
命令如下：rclone.exe mount -v --read-only --vfs-read-chunk-size=4M --buffer-size=32M --network-mode 115drive: E
报错如下：INFO  : 115 /: poll-interval is not supported by this remote
ERROR : Ignoring --network-mode as it is not supported with directory mountpoint
The service rclone has been started.

**Comment by gaoyb7** [comment]
E盘后面没加冒号。。这些问题你先自查吧

**Comment by dalaoJAck** [comment]
加了是这样
INFO  : 115 /: poll-interval is not supported by this remote
Fatal error: failed to mount FUSE fs: mountpoint path already exists: E:

**Comment by gaoyb7** [comment]
> 加了是这样 INFO : 115 /: poll-interval is not supported by this remote Fatal error: failed to mount FUSE fs: mountpoint path already exists: E:

这不是告诉你原因了么。E盘是已经存在的啊，换一个不存在的盘

**Comment by dalaoJAck** [comment]
不好意思刚才粘贴错了，
报的是这个INFO  : 115 /: poll-interval is not supported by this remote
The service rclone has been started.

**Comment by gaoyb7** [comment]
> 不好意思刚才粘贴错了， 报的是这个INFO : 115 /: poll-interval is not supported by this remote The service rclone has been started.

启动成功了啊，拜托你看信息。不要啥都贴上来这里不是教你怎么用的地方

**Comment by dalaoJAck** [comment]
刚才看好像还是挂载本地磁盘失败，不好意思打扰了，我再找找其它方法把
