### ISSUE TITLE
大神，使用1024_Darwin_arm64搭建webdav后，iPad等局域网设备无法连接

### ISSUE THREAD

**Issue by weekqin** [gaoyb7/rclone-release#18]
大神您好，我在mac上成功启动webdav后，本机能正常使用，infuse也能正常播放，但使用ipad的infuse却一直提示无法连结服务器，请问是为何？
我使用的启动命令是
./rclone serve webdav --addr 127.0.0.1:56876 --user abc --pass abcd --read-only --vfs-read-chunk-size=4M --buffer-size=32M -v 115drive:

**Comment by gaoyb7** [comment]
--addr 127.0.0.1:56876
