### ISSUE TITLE
docker的 WebDav  加用户密码登录吗？

### ISSUE THREAD

**Issue by thankforcat** [gaoyb7/rclone-release#19]
大神你好，我成功把网盘挂载为本地 WebDav 服务了。
请问可以怎么加上用户名和密码啊？
我用这个没有作用，不知道是不是我姿势不对。
    -e USERNAME=root -e PASSWORD=password \

**Comment by gaoyb7** [comment]
> 大神你好，我成功把网盘挂载为本地 WebDav 服务了。 请问可以怎么加上用户名和密码啊？ 我用这个没有作用，不知道是不是我姿势不对。 -e USERNAME=root -e PASSWORD=password \

https://rclone.org/commands/rclone_serve_webdav/

**Comment by thankforcat** [comment]
> > 大神你好，我成功把网盘挂载为本地 WebDav 服务了。 请问可以怎么加上用户名和密码啊？ 我用这个没有作用，不知道是不是我姿势不对。 -e USERNAME=root -e PASSWORD=password \
> 
> https://rclone.org/commands/rclone_serve_webdav/#options

感谢您！
