### ISSUE TITLE
mount命令没有

### ISSUE THREAD

**Issue by onceyourgong** [gaoyb7/rclone-release#5]
全村的希望。。。。希望大佬能够尽快修正
rclone命令里面没有mount，windows和linux都试过了，都存在同样的问题。

**Comment by gaoyb7** [comment]
> 全村的希望。。。。希望大佬能够尽快修正 rclone命令里面没有mount，windows和linux都试过了，都存在同样的问题。

linux 可以使用，自行检查依赖问题。Windows不支持
