### ISSUE TITLE
无法复制文件进去

### ISSUE THREAD

**Issue by qq57240** [gaoyb7/rclone-release#6]
10月 03 13:57:38 cloudserver rclone[2899]: ERROR : aria2c: Failed to copy: optional feature not implemented
10月 03 13:57:38 cloudserver rclone[2899]: ERROR : aria2c: vfs cache: failed to upload try #3, will retry in 40s: vfs cache: failed to transfer file from cache to remote: optional feature not implemented
10月 03 13:58:18 cloudserver rclone[2899]: ERROR : aria2c: Failed to copy: optional feature not implemented
10月 03 13:58:18 cloudserver rclone[2899]: ERROR : aria2c: vfs cache: failed to upload try #4, will retry in 1m20s: vfs cache: failed to transfer file from cache to remote: optional feature not implemented
10月 03 13:59:38 cloudserver rclone[2899]: ERROR : aria2c: Failed to copy: optional feature not implemented
10月 03 13:59:38 cloudserver rclone[2899]: ERROR : aria2c: vfs cache: failed to upload try #5, will retry in 2m40s: vfs cache: failed to transfer file from cache to remote: optional feature not implemented
10月 03 13:59:54 cloudserver rclone[2899]: ERROR : MD0009.ts: Failed to copy: optional feature not implemented
10月 03 13:59:54 cloudserver rclone[2899]: ERROR : MD0009.ts: vfs cache: failed to upload try #1, will retry in 10s: vfs cache: failed to transfer file from cache to remote: optional feature not implemented

挂载参数：
rclone mount --allow-other --vfs-cache-mode=writes --allow-non-empty 115drive: /mnt/sdd

**Comment by gaoyb7** [comment]
不支持文件上传
