### ISSUE TITLE
115本地挂载失败

### ISSUE THREAD

**Issue by qearlziper** [gaoyb7/rclone-release#7]
大佬，115本地挂载失败。日志如下：

date | stream | content
-- | -- | --
2022-11-01T10:36:17.595661461Z | stderr | 2022/11/01 10:36:17 INFO  : 115 /: poll-interval is not supported by this remote
2022-11-01T10:36:17.594173756Z | stderr | 2022/11/01 10:36:17 NOTICE: Config file "/config/rclone/rclone.conf" not found - using defaults
2022-11-01T10:35:31.144725211Z | stderr | 2022/11/01 10:35:31 INFO  : Exiting...
2022-11-01T10:35:31.144472473Z | stderr | 2022/11/01 10:35:31 ERROR : /mnt/115drive: Unmounted rclone mount
2022-11-01T10:35:31.121701299Z | stderr | 2022/11/01 10:35:31 INFO  : Signal received: terminated
2022-11-01T10:30:01.527089677Z | stderr | 2022/11/01 10:30:01 INFO  : 115 /: poll-interval is not supported by this remote
2022-11-01T10:30:01.525474023Z | stderr | 2022/11/01 10:30:01 NOTICE: Config file "/config/rclone/rclone.conf" not found - using defaults
2022-11-01T10:29:32.438308302Z | stderr | 2022/11/01 10:29:32 INFO  : Exiting...
2022-11-01T10:29:32.438041400Z | stderr | 2022/11/01 10:29:32 ERROR : /mnt/115drive: Unmounted rclone mount
2022-11-01T10:29:32.421126052Z | stderr | 2022/11/01 10:29:32 INFO  : Signal received: terminated
2022-11-01T10:28:05.226468365Z | stderr | 2022/11/01 10:28:05 INFO  : 115 /: poll-interval is not supported by this remote
2022-11-01T10:28:05.224939955Z | stderr | 2022/11/01 10:28:05 NOTICE: Config file "/config/rclone/rclone.conf" not found - using defaults

下面是设置图

![image](https://user-images.githubusercontent.com/49893706/199215349-2ea9b3ef-d80c-4c2a-971c-706436506dc4.png)

**Comment by jonntd** [comment]
用windows试试

qearlziper ***@***.***> 于2022年11月1日周二 18:39写道：

**Comment by gaoyb7** [comment]
> 大佬，115本地挂载失败。日志如下：
> 
> date	stream	content
> 2022-11-01T10:36:17.595661461Z	stderr	2022/11/01 10:36:17 INFO  : 115 /: poll-interval is not supported by this remote
> 2022-11-01T10:36:17.594173756Z	stderr	2022/11/01 10:36:17 NOTICE: Config file "/config/rclone/rclone.conf" not found - using defaults
> 2022-11-01T10:35:31.144725211Z	stderr	2022/11/01 10:35:31 INFO  : Exiting...
> 2022-11-01T10:35:31.144472473Z	stderr	2022/11/01 10:35:31 ERROR : /mnt/115drive: Unmounted rclone mount
> 2022-11-01T10:35:31.121701299Z	stderr	2022/11/01 10:35:31 INFO  : Signal received: terminated
> 2022-11-01T10:30:01.527089677Z	stderr	2022/11/01 10:30:01 INFO  : 115 /: poll-interval is not supported by this remote
> 2022-11-01T10:30:01.525474023Z	stderr	2022/11/01 10:30:01 NOTICE: Config file "/config/rclone/rclone.conf" not found - using defaults
> 2022-11-01T10:29:32.438308302Z	stderr	2022/11/01 10:29:32 INFO  : Exiting...
> 2022-11-01T10:29:32.438041400Z	stderr	2022/11/01 10:29:32 ERROR : /mnt/115drive: Unmounted rclone mount
> 2022-11-01T10:29:32.421126052Z	stderr	2022/11/01 10:29:32 INFO  : Signal received: terminated
> 2022-11-01T10:28:05.226468365Z	stderr	2022/11/01 10:28:05 INFO  : 115 /: poll-interval is not supported by this remote
> 2022-11-01T10:28:05.224939955Z	stderr	2022/11/01 10:28:05 NOTICE: Config file "/config/rclone/rclone.conf" not found - using defaults
> 下面是设置图
> 
> ![image](https://user-images.githubusercontent.com/49893706/199215349-2ea9b3ef-d80c-4c2a-971c-706436506dc4.png)

挂载的目录必须为空，docker/rclone 下面多了一个 config 目录

**Comment by gaoyb7** [comment]
> 大佬，115本地挂载失败。日志如下：
> 
> date	stream	content
> 2022-11-01T10:36:17.595661461Z	stderr	2022/11/01 10:36:17 INFO  : 115 /: poll-interval is not supported by this remote
> 2022-11-01T10:36:17.594173756Z	stderr	2022/11/01 10:36:17 NOTICE: Config file "/config/rclone/rclone.conf" not found - using defaults
> 2022-11-01T10:35:31.144725211Z	stderr	2022/11/01 10:35:31 INFO  : Exiting...
> 2022-11-01T10:35:31.144472473Z	stderr	2022/11/01 10:35:31 ERROR : /mnt/115drive: Unmounted rclone mount
> 2022-11-01T10:35:31.121701299Z	stderr	2022/11/01 10:35:31 INFO  : Signal received: terminated
> 2022-11-01T10:30:01.527089677Z	stderr	2022/11/01 10:30:01 INFO  : 115 /: poll-interval is not supported by this remote
> 2022-11-01T10:30:01.525474023Z	stderr	2022/11/01 10:30:01 NOTICE: Config file "/config/rclone/rclone.conf" not found - using defaults
> 2022-11-01T10:29:32.438308302Z	stderr	2022/11/01 10:29:32 INFO  : Exiting...
> 2022-11-01T10:29:32.438041400Z	stderr	2022/11/01 10:29:32 ERROR : /mnt/115drive: Unmounted rclone mount
> 2022-11-01T10:29:32.421126052Z	stderr	2022/11/01 10:29:32 INFO  : Signal received: terminated
> 2022-11-01T10:28:05.226468365Z	stderr	2022/11/01 10:28:05 INFO  : 115 /: poll-interval is not supported by this remote
> 2022-11-01T10:28:05.224939955Z	stderr	2022/11/01 10:28:05 NOTICE: Config file "/config/rclone/rclone.conf" not found - using defaults
> 下面是设置图
> 
> ![image](https://user-images.githubusercontent.com/49893706/199215349-2ea9b3ef-d80c-4c2a-971c-706436506dc4.png)

执行命令看不到

**Comment by qearlziper** [comment]
![image](https://user-images.githubusercontent.com/49893706/199385993-adb3237f-d1fb-4ea0-8456-bbb8ec36b6c9.png)

**Comment by gaoyb7** [comment]
> ![image](https://user-images.githubusercontent.com/49893706/199385993-adb3237f-d1fb-4ea0-8456-bbb8ec36b6c9.png)

![image](https://user-images.githubusercontent.com/9281603/199392798-34a4ed76-caa0-42b1-b4ad-82434e7e9287.png)
配置目录和挂载目录不要放一起

**Comment by qearlziper** [comment]
![image](https://user-images.githubusercontent.com/49893706/199407728-251aeaaa-ffdd-4ed8-bd83-b38085f489ad.png)
![image](https://user-images.githubusercontent.com/49893706/199408337-ae5f301f-442b-463d-a306-64b3b5d7bb31.png)

**Comment by gaoyb7** [comment]
> ![image](https://user-images.githubusercontent.com/49893706/199407728-251aeaaa-ffdd-4ed8-bd83-b38085f489ad.png) ![image](https://user-images.githubusercontent.com/49893706/199408337-ae5f301f-442b-463d-a306-64b3b5d7bb31.png) 请问这样设置是对的么，我进入docker/rclone还是没有挂载成功。已排除115cookie问题，感谢大佬抽空回复

这没报错啊。。

**Comment by jonntd** [comment]
不行就试试 alist + rclone

gaoyb7 ***@***.***> 于2022年11月2日周三 16:45写道：
