### ISSUE TITLE
是否支援mac m1呢

### ISSUE THREAD

**Issue by y49711** [gaoyb7/rclone-release#9]
不好意思 稍微嘗試了一下
我使用linux arm64版本
在m1版本的macmini會報 Exec format error
是否有解決方案呢
感謝

**Comment by gaoyb7** [comment]
> 不好意思 稍微嘗試了一下 我使用linux arm64版本 在m1版本的macmini會報 Exec format error 是否有解決方案呢 感謝

已经有了。。rclone_v1_20221024_Darwin_arm64.tar.gz
